### ISSUE TITLE
Seems to be a problem with email address containing . char

### ISSUE THREAD

**Issue by BlokeUK** [lorenzodifuccia/safaribooks#106]
Hi,
I get the following error when trying to use this program, I think it might be because my email address is in the format abcd.efg.hi@email.com
I am using the following example command inside safaribooks directory
python3 safaribooks.py --cred "'abcd.efg.hi@email.com:somepassword" 012345678 :
Error in sys.excepthook:
Traceback (most recent call last):
  File "safaribooks.py", line 104, in unhandled_exception
    self.exit("Unhandled Exception: %s (type: %s)" % (o, o.__class__.__name__))
  File "safaribooks.py", line 90, in exit
    self.error(str(error))
  File "safaribooks.py", line 87, in error
    self.out(output)
  File "safaribooks.py", line 73, in out
    sys.stdout.write("\r" + " " * self.columns + "\r" + str(put, "utf-8", "replace") + "\n")
TypeError: decoding str is not supported

Original exception was:
Traceback (most recent call last):
  File "safaribooks.py", line 1039, in <module>
    SafariBooks(args_parsed)
  File "safaribooks.py", line 281, in __init__
    self.display.intro()
  File "safaribooks.py", line 123, in intro
    self.out(output)
  File "safaribooks.py", line 73, in out
    sys.stdout.write("\r" + " " * self.columns + "\r" + str(put, "utf-8", "replace") + "\n")
TypeError: decoding str is not supported

**Comment by gavinkflam** [comment]
See #101 and [this comment](https://github.com/lorenzodifuccia/safaribooks/issues/101#issuecomment-502340957).

**Comment by paraglohiya** [comment]
I downloaded the latest version and still getting below issue. the email addres didn't had any . in it.
Error in sys.excepthook:
Traceback (most recent call last):
  File "safaribooks.py", line 104, in unhandled_exception
    self.exit("Unhandled Exception: %s (type: %s)" % (o, o.__class__.__name__))
  File "safaribooks.py", line 90, in exit
    self.error(str(error))
  File "safaribooks.py", line 87, in error
    self.out(output)
  File "safaribooks.py", line 73, in out
    sys.stdout.write("\r" + " " * self.columns + "\r" + str(put, "utf-8", "replace") + "\n")
TypeError: decoding str is not supported

Original exception was:
Traceback (most recent call last):
  File "safaribooks.py", line 1039, in <module>
    SafariBooks(args_parsed)
  File "safaribooks.py", line 281, in __init__
    self.display.intro()
  File "safaribooks.py", line 123, in intro
    self.out(output)
  File "safaribooks.py", line 73, in out
    sys.stdout.write("\r" + " " * self.columns + "\r" + str(put, "utf-8", "replace") + "\n")
