### ISSUE TITLE
TypeError: decoding str is not supported

### ISSUE THREAD

**Issue by mohseneslami** [lorenzodifuccia/safaribooks#125]
Hello, I installed safaribooks but when try for 

safaribooks.py --cred "mylogin:pass" 9781492071266 --no-kindle i get this error

TypeError: decoding str is not supported

Error in sys.excepthook:
Traceback (most recent call last):
  File "C:\safaribooks\safaribooks.py", line 104, in unhandled_exception
    self.exit("Unhandled Exception: %s (type: %s)" % (o, o.__class__.__name__))
  File "C:\safaribooks\safaribooks.py", line 90, in exit
    self.error(str(error))
  File "C:\safaribooks\safaribooks.py", line 87, in error
    self.out(output)
  File "C:\safaribooks\safaribooks.py", line 73, in out
    sys.stdout.write("\r" + " " * self.columns + "\r" + str(put, "utf-8", "repla
ce") + "\n")
TypeError: decoding str is not supported

Original exception was:
Traceback (most recent call last):
  File "C:\safaribooks\safaribooks.py", line 1039, in <module>
    SafariBooks(args_parsed)
  File "C:\safaribooks\safaribooks.py", line 281, in __init__
    self.display.intro()
  File "C:\safaribooks\safaribooks.py", line 123, in intro
    self.out(output)
  File "C:\safaribooks\safaribooks.py", line 73, in out
    sys.stdout.write("\r" + " " * self.columns + "\r" + str(put, "utf-8", "repla
ce") + "\n")
TypeError: decoding str is not supported

**Comment by rickyah** [comment]
There is a temporally fix for this:
https://github.com/lorenzodifuccia/safaribooks/issues/115#issuecomment-516397299
