### ISSUE TITLE
TypeError: decoding str is not supported

### ISSUE THREAD

**Issue by szewczyk-it** [lorenzodifuccia/safaribooks#139]
OS: MacOS Mojave (10.14.6)
`python3 --version`

> Python 3.7.4

`pip3 --version`

> pip 19.1.1 from /usr/local/lib/python3.7/site-packages/pip (python 3.7) 

`python3 safaribooks.py --cred 'user@email:password' BOOK_ID`
returns me an error:

> Error in sys.excepthook:
Traceback (most recent call last):
  File "safaribooks.py", line 104, in unhandled_exception
    self.exit("Unhandled Exception: %s (type: %s)" % (o, o.__class__.__name__))
  File "safaribooks.py", line 90, in exit
    self.error(str(error))
  File "safaribooks.py", line 87, in error
    self.out(output)
  File "safaribooks.py", line 73, in out
    sys.stdout.write("\r" + " " * self.columns + "\r" + str(put, "utf-8", "replace") + "\n")
TypeError: decoding str is not supported

Original exception was:
Traceback (most recent call last):
  File "safaribooks.py", line 1039, in <module>
    SafariBooks(args_parsed)
  File "safaribooks.py", line 281, in __init__
    self.display.intro()
  File "safaribooks.py", line 123, in intro
    self.out(output)
  File "safaribooks.py", line 73, in out
    sys.stdout.write("\r" + " " * self.columns + "\r" + str(put, "utf-8", "replace") + "\n")
TypeError: decoding str is not supported

**Comment by shubham-m** [comment]
Looks like the recent commits has introduced this bug. As a mitigation you can roll back 2 versions.

git reset --hard HEAD~2

It would work after that

**Comment by szewczyk-it** [comment]
Works fine, thanks!
