### ISSUE TITLE
Cannot sudo rm -rf some .log file so cannot download my book

### ISSUE THREAD

**Issue by nyck33** [lorenzodifuccia/safaribooks#321]
```
python3 safaribooks.py --cred "nobu.kim66@gmail.com:XXXXXXXX" 9780136905776
Traceback (most recent call last):
  File "safaribooks.py", line 1122, in <module>
    SafariBooks(args_parsed)
  File "safaribooks.py", line 314, in __init__
    self.display = Display("info_%s.log" % escape(args.bookid))
  File "safaribooks.py", line 57, in __init__
    logs_handler = logging.FileHandler(filename=self.log_file)
  File "/home/nobu/anaconda3/envs/safari/lib/python3.8/logging/__init__.py", line 1147, in __init__
    StreamHandler.__init__(self, self._open())
  File "/home/nobu/anaconda3/envs/safari/lib/python3.8/logging/__init__.py", line 1176, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
IsADirectoryError: [Errno 21] Is a directory: '/media/nobu/NTFSUbuWin/Safari/safaribooks/info_9780136905776.log'
```
I cannot sudo rm -rf info_9780136905776.log

When I do ls I see:

```
Books                   LICENSE.md    register_user.py
cookies.json            Pipfile       requirements.txt
info_9780136905776.log  Pipfile.lock  safaribooks.py
info_9781617299339.log  README.md     sso_cookies.py
```

**Comment by lorenzodifuccia** [comment]
### @nyck33 and @everyone, PAY ATTENTION TO DO NOT DISCLOSE YOUR PASSWORD IN ISSUES SCREEN OR SNIPPET....
