### ISSUE TITLE
UnicodeEncodeError on logging events

### ISSUE THREAD

**Issue by TheNullable** [lorenzodifuccia/safaribooks#37]
Always throws error when downloading a new book:

```
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.5/logging/__init__.py", line 983, in emit
    stream.write(msg)
UnicodeEncodeError: 'ascii' codec can't encode character '\xa9' in position 50: ordinal not in range(128)
Call stack:
  File "safaribooks.py", line 1023, in <module>
    SafariBooks(args_parsed)
  File "safaribooks.py", line 292, in __init__
    self.display.book_info(self.book_info)
  File "safaribooks.py", line 135, in book_info
    self.info("{0}{1}{2}: {3}".format(self.SH_YELLOW, t[0], self.SH_DEFAULT, t[1]), True)
  File "safaribooks.py", line 67, in info
    self.log(message)
  File "safaribooks.py", line 61, in log
    self.logger.info(str(message))
Message: '\x1b[33mRights\x1b[0m: Copyright \xa9 2018 Packt Publishing'
```

**Comment by lorenzodifuccia** [comment]
Could you clone again the repository and try with this new fix?
Let me know.
