### ISSUE TITLE
unable to download

### ISSUE THREAD

**Issue by Arshad83** [lorenzodifuccia/safaribooks#43]
Traceback (most recent call last):
  File "safaribooks.py", line 1023, in <module>
    SafariBooks(args_parsed)
  File "safaribooks.py", line 269, in __init__
    self.display = Display("info_%s.log" % escape(args.bookid))
  File "safaribooks.py", line 38, in __init__
    logs_handler = logging.FileHandler(filename=self.log_file)
  File "C:\Users\Arshad\AppData\Local\Programs\Python\Python37-32\lib\logging\__init__.py", line 1092, in __init__
    StreamHandler.__init__(self, self._open())
  File "C:\Users\Arshad\AppData\Local\Programs\Python\Python37-32\lib\logging\__init__.py", line 1121, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
OSError: [Errno 22] Invalid argument: 'C:\\Users\\Arshad\\Downloads\\Compressed\\safaribooks\\info_https:\\www.safaribooksonline.com\\library\\view\\gamification-with-moodle\\9781782173076.log'

**Comment by lorenzodifuccia** [comment]
You ran the program putting all the link as argument, you should insert only the Book ID.
Like: `safaribooks.py 9781782173076`

**Comment by Arshad83** [comment]
Thank it is working now. super
