### ISSUE TITLE
Error when convert Epub to Kindle by Calibre

### ISSUE THREAD

**Issue by giangstrider** [lorenzodifuccia/safaribooks#57]
Hi, thanks for this lib.
Everybook I downloaded when convert with Calibre always get this error.
Do guys have any idea?
```Convert book 1 of 1 (Meta-heuristic and Evolutionary Algorithms for Engineering Optimization)
Conversion options changed from defaults:
  output_profile: 'kindle_voyage'
  cover: u'/var/folders/h0/ytf50xh121v90wvl_sz8lx_80000gn/C/calibre_3.35.0_tmp_WI1XDR/8zm4ie.jpeg'
  read_metadata_from_opf: u'/var/folders/h0/ytf50xh121v90wvl_sz8lx_80000gn/C/calibre_3.35.0_tmp_WI1XDR/N4AnUa.opf'
  verbose: 2
  mobi_toc_at_start: True
Resolved conversion options
calibre version: 3.35.0
{'asciiize': False,
 'author_sort': None,
 'authors': None,
 'base_font_size': 0.0,
 'book_producer': None,
 'change_justification': u'original',
 'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
 'chapter_mark': u'pagebreak',
 'comments': None,
 'cover': u'/var/folders/h0/ytf50xh121v90wvl_sz8lx_80000gn/C/calibre_3.35.0_tmp_WI1XDR/8zm4ie.jpeg',
 'debug_pipeline': None,
 'dehyphenate': True,
 'delete_blank_paragraphs': True,
 'disable_font_rescaling': False,
 'dont_compress': False,
 'duplicate_links_in_toc': False,
 'embed_all_fonts': False,
 'embed_font_family': None,
 'enable_heuristics': False,
 'expand_css': False,
 'extra_css': None,
 'extract_to': None,
 'filter_css': u'',
 'fix_indents': True,
 'font_size_mapping': None,
 'format_scene_breaks': True,
 'html_unwrap_factor': 0.4,
 'input_encoding': None,
 'input_profile': <calibre.customize.profiles.InputProfile object at 0x10c99a790>,
 'insert_blank_line': False,
 'insert_blank_line_size': 0.5,
 'insert_metadata': False,
 'isbn': None,
 'italicize_common_cases': True,
 'keep_ligatures': False,
 'language': None,
 'level1_toc': None,
 'level2_toc': None,
 'level3_toc': None,
 'line_height': 0.0,
 'linearize_tables': False,
 'margin_bottom': 5.0,
 'margin_left': 5.0,
 'margin_right': 5.0,
 'margin_top': 5.0,
 'markup_chapter_headings': True,
 'max_toc_links': 50,
 'minimum_line_height': 120.0,
 'mobi_file_type': u'old',
 'mobi_ignore_margins': False,
 'mobi_keep_original_images': False,
 'mobi_toc_at_start': True,
 'no_chapters_in_toc': False,
 'no_inline_navbars': True,
 'no_inline_toc': False,
 'output_profile': <calibre.customize.profiles.KindleVoyageOutput object at 0x10c99afd0>,
 'page_breaks_before': u'/',
 'personal_doc': u'[PDOC]',
 'prefer_author_sort': False,
 'prefer_metadata_cover': False,
 'pretty_print': False,
 'pubdate': None,
 'publisher': None,
 'rating': None,
 'read_metadata_from_opf': u'/var/folders/h0/ytf50xh121v90wvl_sz8lx_80000gn/C/calibre_3.35.0_tmp_WI1XDR/N4AnUa.opf',
 'remove_fake_margins': True,
 'remove_first_image': False,
 'remove_paragraph_spacing': False,
 'remove_paragraph_spacing_indent_size': 1.5,
 'renumber_headings': True,
 'replace_scene_breaks': u'',
 'search_replace': '[]',
 'series': None,
 'series_index': None,
 'share_not_sync': False,
 'smarten_punctuation': False,
 'sr1_replace': None,
 'sr1_search': None,
 'sr2_replace': None,
 'sr2_search': None,
 'sr3_replace': None,
 'sr3_search': None,
 'start_reading_at': None,
 'subset_embedded_fonts': False,
 'tags': None,
 'timestamp': None,
 'title': None,
 'title_sort': None,
 'toc_filter': None,
 'toc_threshold': 6,
 'toc_title': None,
 'transform_css_rules': '[]',
 'unsmarten_punctuation': False,
 'unwrap_lines': True,
 'use_auto_toc': False,
 'verbose': 2}
Python function terminated unexpectedly: Invalid namespace u'http://idpf.org/2007/opf' for OPF document
InputFormatPlugin: EPUB Input running
on /var/folders/h0/ytf50xh121v90wvl_sz8lx_80000gn/C/calibre_3.35.0_tmp_WI1XDR/yhnFRD.epub
Found HTML cover OEBPS/cover.xhtml
Parsing all content...
Traceback (most recent call last):
  File "/Applications/calibre.app/Contents/Resources/Python/lib/python2.7/site.py", line 154, in main
    return run_entry_point()
  File "/Applications/calibre.app/Contents/Resources/Python/lib/python2.7/site.py", line 114, in run_entry_point
    return getattr(pmod, func)()
  File "site-packages/calibre/utils/ipc/worker.py", line 199, in main
  File "site-packages/calibre/gui2/convert/gui_conversion.py", line 42, in gui_convert_override
  File "site-packages/calibre/gui2/convert/gui_conversion.py", line 27, in gui_convert
  File "site-packages/calibre/ebooks/conversion/plumber.py", line 1117, in run
  File "site-packages/calibre/ebooks/conversion/plumber.py", line 1311, in create_oebbook
  File "site-packages/calibre/ebooks/oeb/reader.py", line 72, in __call__
  File "site-packages/calibre/ebooks/oeb/reader.py", line 133, in _read_opf
calibre.ebooks.oeb.base.OEBError: Invalid namespace u'http://idpf.org/2007/opf' for OPF document```

**Comment by lorenzodifuccia** [comment]
I don't know if this issue is related exclusively to my script or even to Calibre.
Pull the repo (11993f1), try again and let me know!

**Comment by lorenzodifuccia** [comment]
Good! Thanks for the issue.
Let's mark this as closed, will you agree @giangstrider?

**Comment by giangstrider** [comment]
Yes, closed!
