### ISSUE TITLE
TypeError: Can't convert 'bytes' object to str implicitly

### ISSUE THREAD

**Issue by neeldesh** [lorenzodifuccia/safaribooks#75]
After the commit on Feb 13, the tool doesn't work for me. I went back to the old version and it worked again.

I get this error with the new version:

```bash
user@server:/opt/safaribooks$ python3 safaribooks.py --cred "user@mail.com:password01" XXXXXXXXXXXXX
Error in sys.excepthook:
Traceback (most recent call last):
  File "safaribooks.py", line 98, in unhandled_exception
    self.exit("Unhandled Exception: %s (type: %s)" % (o, o.__class__.__name__))
  File "safaribooks.py", line 84, in exit
    self.error(str(error))
  File "safaribooks.py", line 81, in error
    self.out(output)
  File "safaribooks.py", line 67, in out
    sys.stdout.write("\r" + " " * self.columns + "\r" + put.encode("utf-8", "replace") + "\n")
TypeError: Can't convert 'bytes' object to str implicitly

Original exception was:
Traceback (most recent call last):
  File "safaribooks.py", line 1026, in <module>
    SafariBooks(args_parsed)
  File "safaribooks.py", line 274, in __init__
    self.display.intro()
  File "safaribooks.py", line 117, in intro
    self.out(output)
  File "safaribooks.py", line 67, in out
    sys.stdout.write("\r" + " " * self.columns + "\r" + put.encode("utf-8", "replace") + "\n")
TypeError: Can't convert 'bytes' object to str implicitly
```

**Comment by hien** [comment]
I'm facing same issue.

**Comment by kendallm** [comment]
https://github.com/lorenzodifuccia/safaribooks/pull/76

Just created a pull request to fix this issue

**Comment by lorenzodifuccia** [comment]
e4c8c55 should fix this issue.

**Comment by lorenzodifuccia** [comment]
Pull last commit: b96819b
